# Generated by Django 4.2.2 on 2023-06-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='transaction_date',
        ),
    ]
