# Generated by Django 4.2.2 on 2023-06-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_transaction_receiver_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
